# Generated by Django 4.0.5 on 2022-09-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_createstockgrp_item_group_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='ledger_cr_db',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
    ]
