# Generated by Django 4.0.5 on 2022-09-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_ledger_ledger_tax_register_ledger_tax_ledger_sundry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='voucher2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date2', models.CharField(blank=True, default='Null', max_length=225)),
                ('Particulars2', models.CharField(blank=True, default='Null', max_length=225)),
                ('VchType2', models.CharField(blank=True, default='Null', max_length=225)),
                ('VchNo2', models.CharField(blank=True, default='Null', max_length=225)),
                ('Debit2', models.CharField(blank=True, default='Null', max_length=225)),
                ('Credit2', models.CharField(blank=True, default='Null', max_length=225)),
            ],
        ),
    ]
