# Generated by Django 4.0.5 on 2022-09-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_voucher2'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=225)),
                ('particular', models.CharField(max_length=225)),
                ('voucher_type', models.CharField(max_length=225)),
                ('voucher_number', models.CharField(max_length=225)),
                ('quntity', models.CharField(max_length=225)),
                ('value', models.CharField(max_length=225)),
            ],
        ),
    ]
