# Generated by Django 4.0.5 on 2022-09-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_add_voucher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='voucher2',
        ),
        migrations.RemoveField(
            model_name='add_voucher',
            name='date',
        ),
        migrations.RemoveField(
            model_name='add_voucher',
            name='particular',
        ),
        migrations.RemoveField(
            model_name='add_voucher',
            name='quntity',
        ),
        migrations.RemoveField(
            model_name='add_voucher',
            name='value',
        ),
        migrations.RemoveField(
            model_name='add_voucher',
            name='voucher_number',
        ),
        migrations.RemoveField(
            model_name='add_voucher',
            name='voucher_type',
        ),
        migrations.AddField(
            model_name='add_voucher',
            name='credit2',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='add_voucher',
            name='date2',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='add_voucher',
            name='debit2',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='add_voucher',
            name='particulars2',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='add_voucher',
            name='vchNo2',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='add_voucher',
            name='vchType2',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
    ]
