# Generated by Django 4.0.5 on 2022-09-13 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_voucher2_remove_add_voucher_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_voucher',
        ),
    ]
