# Generated by Django 4.0.5 on 2022-09-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_add_voucher_add_voucher2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_voucher',
        ),
        migrations.DeleteModel(
            name='add_voucher2',
        ),
        migrations.RemoveField(
            model_name='compute_information',
            name='Pay_head_id',
        ),
        migrations.DeleteModel(
            name='crtcompony',
        ),
        migrations.RemoveField(
            model_name='gratuity',
            name='pay_head_id',
        ),
        migrations.RemoveField(
            model_name='group_summary',
            name='CreateStockGrp',
        ),
        migrations.RemoveField(
            model_name='ledger_banking_details',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_mailing_address',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_rounding',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_satutory',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_sundry',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_tax',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_tax_register',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='rounding',
            name='pay_head_id',
        ),
        migrations.DeleteModel(
            name='stock_item_crt',
        ),
        migrations.DeleteModel(
            name='compute_information',
        ),
        migrations.DeleteModel(
            name='create_payhead',
        ),
        migrations.DeleteModel(
            name='CreateStockGrp',
        ),
        migrations.DeleteModel(
            name='gratuity',
        ),
        migrations.DeleteModel(
            name='group_summary',
        ),
        migrations.DeleteModel(
            name='Ledger',
        ),
        migrations.DeleteModel(
            name='Ledger_Banking_Details',
        ),
        migrations.DeleteModel(
            name='Ledger_Mailing_Address',
        ),
        migrations.DeleteModel(
            name='Ledger_Rounding',
        ),
        migrations.DeleteModel(
            name='Ledger_Satutory',
        ),
        migrations.DeleteModel(
            name='Ledger_sundry',
        ),
        migrations.DeleteModel(
            name='ledger_tax',
        ),
        migrations.DeleteModel(
            name='Ledger_Tax_Register',
        ),
        migrations.DeleteModel(
            name='Rounding',
        ),
    ]
