# Generated by Django 4.0.5 on 2022-09-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='closebalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.CharField(blank=True, default='0', max_length=225)),
                ('credit', models.CharField(blank=True, default='0', max_length=225)),
            ],
        ),
    ]
