# Generated by Django 4.0.4 on 2022-09-18 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_delete_stock_item_crt_closebalance_ledger_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_path', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('mailing_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10, null=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('fax', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=240, null=True)),
                ('website', models.CharField(max_length=100, null=True)),
                ('currency_symbol', models.CharField(max_length=20)),
                ('formal_name', models.CharField(max_length=20)),
                ('fin_begin', models.DateField()),
                ('books_begin', models.DateField()),
                ('fin_end', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='tally_ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255, null=True)),
                ('under', models.CharField(max_length=255)),
                ('mname', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('pincode', models.CharField(max_length=6, null=True)),
                ('bank_details', models.CharField(max_length=20, null=True)),
                ('pan_no', models.CharField(max_length=100, null=True)),
                ('registration_type', models.CharField(max_length=100, null=True)),
                ('gst_uin', models.CharField(max_length=100, null=True)),
                ('set_alter_gstdetails', models.CharField(max_length=100, null=True)),
                ('opening_blnc', models.IntegerField(null=True)),
                ('set_odl', models.CharField(max_length=255, null=True)),
                ('ac_holder_nm', models.CharField(max_length=255, null=True)),
                ('acc_no', models.CharField(max_length=255, null=True)),
                ('ifsc_code', models.CharField(max_length=255, null=True)),
                ('swift_code', models.CharField(max_length=255, null=True)),
                ('bank_name', models.CharField(max_length=255, null=True)),
                ('branch', models.CharField(max_length=255, null=True)),
                ('SA_cheque_bk', models.CharField(max_length=20, null=True)),
                ('Echeque_p', models.CharField(max_length=20, null=True)),
                ('SA_chequeP_con', models.CharField(max_length=20, null=True)),
                ('type_of_ledger', models.CharField(max_length=100, null=True)),
                ('rounding_method', models.CharField(max_length=100, null=True)),
                ('rounding_limit', models.IntegerField(blank=True, default=None, null=True)),
                ('type_duty_tax', models.CharField(max_length=100, null=True)),
                ('tax_type', models.CharField(max_length=100, null=True)),
                ('valuation_type', models.CharField(max_length=100, null=True)),
                ('rate_per_unit', models.IntegerField(blank=True, default=None, null=True)),
                ('percentage_of_calcution', models.CharField(max_length=100, null=True)),
                ('rond_method', models.CharField(max_length=100, null=True)),
                ('rond_limit', models.IntegerField(blank=True, default=None, null=True)),
                ('gst_applicable', models.CharField(max_length=100, null=True)),
                ('setalter_gstdetails', models.CharField(max_length=20, null=True)),
                ('type_of_supply', models.CharField(max_length=100, null=True)),
                ('assessable_value', models.CharField(max_length=100, null=True)),
                ('appropriate_to', models.CharField(max_length=100, null=True)),
                ('method_of_calculation', models.CharField(max_length=100, null=True)),
                ('balance_billbybill', models.CharField(max_length=100, null=True)),
                ('credit_period', models.CharField(max_length=100, null=True)),
                ('creditdays_voucher', models.CharField(max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.companies')),
            ],
        ),
        migrations.RemoveField(
            model_name='ledger_mailing_address',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_rounding',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_satutory',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_sundry',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_tax',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_tax_register',
            name='ledger_id',
        ),
        migrations.DeleteModel(
            name='Ledger_Banking_Details',
        ),
        migrations.DeleteModel(
            name='Ledger_Mailing_Address',
        ),
        migrations.DeleteModel(
            name='Ledger_Rounding',
        ),
        migrations.DeleteModel(
            name='Ledger_Satutory',
        ),
        migrations.DeleteModel(
            name='Ledger_sundry',
        ),
        migrations.DeleteModel(
            name='ledger_tax',
        ),
        migrations.DeleteModel(
            name='Ledger_Tax_Register',
        ),
        migrations.AlterField(
            model_name='closebalance',
            name='ledger_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tally_ledger'),
        ),
        migrations.DeleteModel(
            name='Ledger',
        ),
    ]
